# Generated by Django 5.1.1 on 2024-09-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_payment_date_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_payment',
            field=models.DateField(verbose_name='Дата оплаты'),
        ),
    ]
