# Generated by Django 5.1.1 on 2024-10-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_payment_link_payment_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата последнего входа'),
        ),
    ]
