# Generated by Django 5.1.1 on 2024-09-27 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('users', '0004_alter_payment_date_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сourse',
            new_name='Course',
        ),
    ]
