# Generated by Django 5.1.1 on 2024-10-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
